### ISSUE TITLE
PC Creation issue, Cannot create PDF on button select

### ISSUE THREAD

**Issue by BobHood** [gizmomathboy/hyperborea_apps#4]
Hi Gizmo,
I'm trying to create some NPC's and just started not working after doing the selections and having the stats generated, Selecting the Create PDF with these stats button heads to a dead page...

EX this URL (created Randomly) drops me onto a Baby Blue Page with nothing. Are you doing Updates?

https://www.gizmomathboy.com/pc_gen/pc?stat_file=name%3A%20Ingitrude%20the%20Apt%0D%0Aclass%3A%20pyromancer%0D%0Alevel%3A%202%0D%0ARace%3A%20Carolingian-Frank%0D%0AGender%3A%20female%0D%0A

**Comment by gizmomathboy** [comment]
Ok, I think I sorted things out. Give it a try and see if it works for you.

**Comment by gizmomathboy** [comment]
Also, it looks like that link is for a set of attributes that didn't meet requirements. I've fixed the app to not display the "create pdf" link when that happens.

**Comment by BobHood** [comment]
I had it set for Strictness 2, so should have only had good stats... Trying now...

**Comment by BobHood** [comment]
Yep, working now...

**Comment by gizmomathboy** [comment]
Excellent.

Some day I'll have a better "upgrade on the web server" path.

Cool, I get to close an issue.
