### ISSUE TITLE
Character Sheet Issues

### ISSUE THREAD

**Issue by Sarsem** [gizmomathboy/hyperborea_apps#7]
[Artemisia - Oon Barbarian 9.pdf](https://github.com/gizmomathboy/hyperborea_apps/files/9204263/Artemisia.-.Oon.Barbarian.9.pdf)
See attached character sheet, with the following issues:

- The AC is entered as 9, but should be 5, based on studded leather (6) and small shield (+1)
- The 3/2 melee attack rate for level isn't accounted for in the weapon combat table (both dagger and bastard sword are listed as 1/1)
- Tribal Leader class ability says "Challenge a tribale...", should be "tribal"

**Comment by Sarsem** [comment]
Another PC sheet with issues:
[032243498 - Oon Priest 9.pdf](https://github.com/gizmomathboy/hyperborea_apps/files/9204348/032243498.-.Oon.Priest.9.pdf)

- The spells all have their level listed as "Pr"

**Comment by gizmomathboy** [comment]
Fixed the typo in the barbarian class abilities.

Figured out what was different for the spell stuff. The processing of default spells was different enough from how I processed a spell list defined in the yaml file.

**Comment by gizmomathboy** [comment]
Didn't get to the attack rate problem. I need to see what is different between my local version and the online version with respect to the AC problem.

**Comment by gizmomathboy** [comment]
I think I sorted out the increased attack rates and armor problems.

**Comment by Sarsem** [comment]
Priest spells are now properly cited; AC is correctly calculated; weapon mastery is applied (though has to be inferred from weapon table modifiers); "tribal" spelling corrected. Consider these issues resolved.

**Comment by Sarsem** [comment]
New issues, with Monk: name has hyphen in it, isn't properly spelled out; empty hand/caestuses attack rate and damage aren't correct; FA is 6, should be 8; class abilities include "accurate strike" (from 2e), but not "extraordinary" strength or dexterity feats, enlisted henchmen; empty hand is described as per 2e
[Sit'u Gooch - Monk 9.pdf](https://github.com/gizmomathboy/hyperborea_apps/files/9229818/Sit.u.Gooch.-.Monk.9.pdf)

**Comment by gizmomathboy** [comment]
It was confirmed output is what is expected.

Closing
